/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-06-16 02:58:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.site.web.robot;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.StringEscapeUtils;
import jease.cms.domain.Content;
import jease.cms.domain.News;
import jease.cms.domain.Topic;
import jease.cms.domain.Folder;
import jease.site.Navigations;
import jfix.servlet.Servlets;
import jease.cms.domain.Content;
import jease.site.Navigations;
import java.net.URL;
import jfix.util.I18N;
import jfix.html.Html2Pdf;
import jfix.servlet.Servlets;
import jease.cms.domain.Content;
import jease.site.Navigations;

public final class Page_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


	final static String currentYear = String.format("%tY ", new java.util.Date());

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("/site/service/Pagebase.jsp", Long.valueOf(1357292604000L));
    _jspx_dependants.put("/site/service/Pdf.jsp", Long.valueOf(1357291944000L));
    _jspx_dependants.put("/site/service/Feeds.jsp", Long.valueOf(1344034858000L));
    _jspx_dependants.put("/site/service/Lightbox.jsp", Long.valueOf(1357181094000L));
    _jspx_dependants.put("/site/service/Rewrite.jsp", Long.valueOf(1357181328000L));
    _jspx_dependants.put("/site/service/Designswitch.jsp", Long.valueOf(1357181026000L));
    _jspx_dependants.put("/site/service/Jquery.jsp", Long.valueOf(1357181076000L));
    _jspx_dependants.put("/site/service/Copyright.jsp", Long.valueOf(1344034858000L));
    _jspx_dependants.put("/site/service/Prettify.jsp", Long.valueOf(1357181316000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	Content content = (Content) request.getAttribute("Node"); 
	Content root = (Content) request.getAttribute("Root");

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(Servlets.getContextURL(request) );
      out.print(Navigations.getBasePath((Content) request.getAttribute("Node")) );
      out.write("\" />");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<title>");
      out.print(Navigations.getPageTitle(content) );
      out.write("</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/site/web/robot/style/screen.css\" media=\"screen\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/site/web/robot/style/print.css\" media=\"");
      out.print( request.getParameter("print") == null ? "print" : "print,screen" );
      out.write("\" />\r\n");
      out.write("<link rel=\"alternate\" type=\"application/rss+xml\"  href=\"");
      out.print( request.getContextPath() );
      out.write("/site/service/feeds/rss.jsp\" title=\"RSS Feed\" />\n");
      out.write("<link rel=\"alternate\" type=\"application/atom+xml\" href=\"");
      out.print( request.getContextPath() );
      out.write("/site/service/feeds/atom.jsp\" title=\"ATOM Feed\" />");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print( request.getContextPath() );
      out.write("/site/service/jquery/jquery-min.js\"></script>");
      out.write("<script type=\"text/javascript\">//<![CDATA[\n");
      out.write("$(document).ready(function(){\n");
      out.write("\t$(\"a[href^=\\./\\~]\").each(function() { \n");
      out.write("\t\tthis.href = \"");
      out.print(request.getContextPath());
      out.write("\" + this.href.substring(this.href.indexOf(\"~\") + 1);\n");
      out.write("\t});\n");
      out.write("});\n");
      out.write("//]]></script>");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/site/service/lightbox/css/prettyPhoto.css\" type=\"text/css\" media=\"screen\" />\n");
      out.write("<style type=\"text/css\">.currentTextHolder {font-size: 12px;}</style>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print( request.getContextPath() );
      out.write("/site/service/lightbox/js/jquery.prettyPhoto.js\"></script>\n");
      out.write("<script type=\"text/javascript\">//<![CDATA[\n");
      out.write("$(document).ready(function(){\n");
      out.write("\tvar config = {\n");
      out.write("\t\t\tshow_title: true,\n");
      out.write("\t\t\tdeeplinking: false,\n");
      out.write("\t\t\tdefault_width: 640,\n");
      out.write("\t\t\tdefault_height: 480,\n");
      out.write("\t\t\toverlay_gallery: true, \n");
      out.write("\t\t\thideflash: true,\n");
      out.write("\t\t\tsocial_tools: ''\n");
      out.write("\t};\n");
      out.write("\t$(\"a.Image\").attr({\"rel\" : \"prettyPhoto[image]\"}).prettyPhoto(config);\n");
      out.write("\t$(\"a[href$=.jpg] img,a[href$=.gif] img,a[href$=.png] img\").parent().attr({\"rel\" : \"prettyPhoto[image]\"}).prettyPhoto(config);\n");
      out.write("\t$(\"a[href$=?print]\").attr({\"rel\" : \"prettyPhoto[iframe]\"}).each(function() { this.href += \"&iframe=true\";}).prettyPhoto(config);\n");
      out.write("\t");
 if (request.getParameter("print") != null) { 
      out.write("\n");
      out.write("\t\t$(\"a\").click(function(evt) {\n");
      out.write("\t\t\tif(!this.target) {\n");
      out.write("\t\t\t\twindow.parent.$.prettyPhoto.close();\n");
      out.write("\t\t\t\twindow.parent.location = this.href;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t");
 } 
      out.write("\n");
      out.write("});\n");
      out.write("//]]></script>");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/site/service/prettify/prettify.css\" media=\"all\"/>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/site/service/prettify/prettify.js\"></script> \n");
      out.write("<script type=\"text/javascript\">//<![CDATA[\n");
      out.write("$(document).ready(function(){\t\n");
      out.write("\t$(\"code,pre\").addClass(\"prettyprint\");\n");
      out.write("\tprettyPrint();\n");
      out.write("});\n");
      out.write("//]]></script>");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/site/web/robot/js/maxheight.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/site/web/robot/js/cufon-yui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/site/web/robot/js/Myriad_Pro_300.font.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/site/web/robot/js/Myriad_Pro_400.font.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">//<![CDATA[\r\n");
      out.write("Cufon.replace(\"#tabs\", { fontFamily: 'Myriad Pro', hover:true });\r\n");
      out.write("Cufon.replace(\"#logo\", { fontFamily: 'Myriad Pro', hover:true });\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\tnew ElementMaxHeight();\r\n");
      out.write("\tCufon.now();\r\n");
      out.write("});\r\n");
      out.write("//]]></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t<div class=\"bg\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div id=\"top\">\r\n");
      out.write("\t\t\t\t\t<div class=\"wrapper\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"fleft\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/site/web/robot/style/img/logo.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.print(root.getPath());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 for(char c : root.getTitle().toCharArray()) { 
      out.write("<span");
      out.print( Character.isLowerCase(c) ? " style=\"color: white;\"" : "" );
      out.write('>');
      out.print(c );
      out.write("</span>");
 } 
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"fright\">\r\n");
      out.write("\t\t\t\t\t\t\t<form action=\"");
      out.print(request.getContextPath() );
      out.print(root.getPath());
      out.write("\" id=\"search-form\">\r\n");
      out.write("\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"text\" name=\"query\" value=\"");
      out.print(request.getParameter("query") != null ? StringEscapeUtils.escapeXml(request.getParameter("query")) : "");
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"page\" value=\"/site/service/Search.jsp\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"submit\" value=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"tabs\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t");
 for (Content tab : Navigations.getTabs(root)) { 
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.print(tab.getPath());
      out.write('"');
      out.write('>');
      out.print(tab.getTitle());
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"news\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t");
 for (News item : Navigations.getNews((Content) content.getParent())) { 
      out.write("<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.print(item.getPath());
      out.write("?print\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 if (item.getDate() != null) { 
      out.print(String.format("%1$td %1$tb %1$tY", item.getDate()));
      out.write(' ');
      out.write('-');
      out.write(' ');
 } 
      out.print(item.getTitle());
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print( StringUtils.isNotBlank(item.getTeaser()) ? item.getTeaser() : item.getStory());
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"content\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"wrapper\">\r\n");
      out.write("\t\t\t\t<div class=\"aside maxheight\">\r\n");
      out.write("\t\t\t\t\t<div class=\"indent\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t\t\t\t");
 for (Content parent : Navigations.getBreadcrumb(root, content)) { 
 if(parent != content.getParent()) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&raquo; <a href=\"");
      out.print(request.getContextPath() );
      out.print(parent.getPath());
      out.write('"');
      out.write('>');
      out.print(parent.getTitle());
      out.write("</a> \r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } 
 } 
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<h1>");
      out.print(((Content) content.getParent()).getTitle());
      out.write("</h1>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t");
 for (Content item : Navigations.getItems((Content) content.getParent())) { 
 if (item instanceof Topic) { 
      out.write("</ul><h2>");
      out.print(item.getTitle());
      out.write("</h2><ul>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } else { 
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.print(item.getPath());
      out.write('"');
      out.write(' ');
      out.print(item == content ? " class=\"current\"" : "");
      out.write('>');
      out.print(item.getTitle());
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
 } 
      out.write("</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"mainContent maxheight\">\r\n");
      out.write("\t\t\t\t\t<div class=\"indent\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"section\">\r\n");
      out.write("\t\t\t\t\t\t\t");
 pageContext.include((String) request.getAttribute("Page.Template")); 
      out.write("<div style=\"clear: both\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"editorial\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 Content latestChange = Navigations.getLatestContribution(content); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tLast modified on ");
      out.print(String.format("%tF", latestChange.getLastModified()));
 if (latestChange.getEditor() != null) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\tby ");
      out.print(latestChange.getEditor().getName());
 }
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"footer\">\r\n");
      out.write("\t\t<div class=\"bg\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"indent\">\r\n");
      out.write("\t\t\t\t\t");
      out.write("\n");
      out.write("&copy; ");
      out.print( currentYear );
      out.write("<a href=\"http://jease.org/\">jease.org</a>");
      out.write(' ');
      out.write('|');
      out.write(' ');

	String pdfPath = request.getParameter("path");
	if (pdfPath != null) {
		Content pdfContent = (Content) Navigations.getRoot().getChild(pdfPath);
		URL pdfUrl = new URL(request.getScheme() + "://" + Servlets.getHost(request) 
								+ request.getContextPath() + Navigations.getBasePath(pdfContent));
		byte[] pdfBytes = new Html2Pdf(pdfUrl).getBytes();
		response.setContentType("application/pdf");
		response.setHeader("Content-Disposition","inline; filename=" + pdfContent.getId() + ".pdf"); 
		response.setContentLength(pdfBytes.length);
		response.getOutputStream().write(pdfBytes);
		return;
	} else {

      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/site/service/Pdf.jsp?path=");
      out.print(((Content) request.getAttribute("Node")).getPath() );
      out.write("\" rel=\"noindex, nofollow\">");
      out.print(I18N.get("Page_as_PDF"));
      out.write("</a>\n");
 } 
      out.write(" | Design by <a href=\"http://www.templates.com/\">templates.com</a>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("  \t\t\t\t\t");
 if (!jease.Registry.getParameter(jease.Names.JEASE_SITE_DESIGN,"").startsWith("/")) { 
      out.write("\n");
      out.write("Design\n");
 for (String design : new String[] { "bright", "cool", "loop", "photo", "robot", "simple" }) { 
      out.write("\n");
      out.write(" | <a href=\"?design=");
      out.print(design);
      out.write('"');
      out.write('>');
      out.print(design);
      out.write("</a>\n");
 } 
 } 
      out.write("</div>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
