/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-06-18 17:59:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.site.domain;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import jease.cms.domain.Image;
import jease.cms.domain.Gallery;

public final class Gallery_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	Gallery gallery = (Gallery) request.getAttribute("Node");
	if (session.getAttribute(gallery.getPath()) != null) {
		gallery = (Gallery) session.getAttribute(gallery.getPath());
	}
	int scale = gallery.getScale();

      out.write("<div class=\"Gallery\">\n");
      out.write("<h1 class=\"Title\">");
      out.print(gallery.getTitle() );
      out.write("</h1>\n");
      out.write("<div class=\"Preface\">");
      out.print(gallery.getPreface() );
      out.write("</div>\n");
 for (Image image : ((Gallery) request.getAttribute("Node")).getChildren(Image.class)) { 
      out.write("<a class=\"Image\" href=\"");
      out.print(request.getContextPath() );
      out.print(image.getPath());
      out.write("\" style=\"");
      out.print( image.isVisible() ? "" : " display: none");
      out.write("\">\n");
      out.write("\t\t");
 if (gallery.isLabeled()) { 
      out.write("<span class=\"Label\">");
      out.print(image.getTitle());
      out.write("<br /></span>\n");
      out.write("\t\t");
 } 
      out.write("<img src=\"");
      out.print(request.getContextPath() );
      out.print(image.getPath());
      out.write("?scale=");
      out.print( scale );
      out.write('"');
 if (gallery.isLabeled()) { 
      out.write(" title=\"");
      out.print(image.getTitle());
      out.write("\" alt=\"");
      out.print(image.getTitle());
      out.write('"');
 } 
      out.write(" />\n");
      out.write("\t</a>\n");
 } 
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
