/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-06-16 04:19:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.site.domain;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.commons.lang3.StringEscapeUtils;
import org.apache.commons.io.FileUtils;
import jease.cmf.service.Compilers;
import jease.cms.domain.Script;

public final class Script_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


	final String SCRIPT_DEFAULT_EXTENSION = ".jsp";
	final String SCRIPT_WEBINF_FOLDER = "/WEB-INF/tmp/";

	java.io.File workDirectory;
	
	public void jspInit() {
		workDirectory = new java.io.File(getServletContext().getRealPath("/")
				+ SCRIPT_WEBINF_FOLDER.replace("/", java.io.File.separator));
		workDirectory.deleteOnExit();
	}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	Script script = (Script) request.getAttribute("Node");
	if (session.getAttribute(script.getPath()) != null) {
		script = (Script) session.getAttribute(script.getPath());
	}
	
	java.io.File scriptDirectory = new java.io.File(workDirectory, script.getUUID());
	scriptDirectory.mkdirs();
	scriptDirectory.deleteOnExit();
	
	String scriptId = script.getId();
	if (scriptId.lastIndexOf(".") == -1) {
		scriptId += SCRIPT_DEFAULT_EXTENSION;
	}

	java.io.File scriptFile = new java.io.File(scriptDirectory, scriptId);
	scriptFile.deleteOnExit();
	if (scriptFile.lastModified() < script.getLastModified().getTime()) {
		scriptFile.delete();
		FileUtils.writeStringToFile(scriptFile, script.getCode(), "UTF-8");
	}

	try {
		if (scriptFile.getName().endsWith(".java")) {
			HttpServlet servlet = (HttpServlet) Compilers.eval(scriptFile);
			servlet.init(config);
			servlet.service(request, response);
			servlet.destroy();
		} else {
			String resourcePath = SCRIPT_WEBINF_FOLDER + script.getUUID() + "/" + scriptId;
			if (script.isForward() || request.getParameter("file") != null) {
				pageContext.forward(resourcePath);
			} else {
				pageContext.include(resourcePath);
			}
		}
	} catch (Exception e) {
		response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
		out.println("<pre>" + StringEscapeUtils.escapeXml(e.getMessage()) + "</pre>");
	}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
