/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-06-18 19:59:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.custom;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import jfix.servlet.*;
import jfix.util.*;
import custom.*;

public final class MasterThesis_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


 MasterThesis masterThesis =
   (MasterThesis) request.getAttribute("Node");
   
    if (session.getAttribute(masterThesis.getPath()) != null) {
        masterThesis = (MasterThesis) session.getAttribute(masterThesis.getPath());
    }
    if (request.getParameter("file") != null) {
         if (request.getParameter("scale") != null) {
                int scale = Integer.parseInt(request.getParameter("scale"));
                Servlets.write(Images.scale(masterThesis.getAuthorPhoto(), scale), "image/jpeg", response);
        } else {
                Servlets.write(masterThesis.getAuthorPhoto(), "image/jpeg", response);
        }
        return;
    }

      out.write("<div>\n");
      out.write("\t<h1>");
      out.print(masterThesis.getTitle());
      out.write("</h1>\n");
      out.write("\t<div>\n");
      out.write("\t\t<p style=\"text-align: justify;\">\n");
      out.write("\t\t<img src=\"");
      out.print(request.getContextPath() );
      out.print(masterThesis.getPath());
      out.write("?file&scale=100\" alt=\"");
      out.print(masterThesis.getTitle());
      out.write("\" title=\"");
      out.print(masterThesis.getTitle());
      out.write("\" width=\"100\" height=\"100\" align=\"right\" style=\"margin:0 0 10px 10px;\"/>\n");
      out.write("\t\t\n");
      out.write("\t\t<strong>Author:</strong> <a href=\"http://github.com/GerardSoleCa\" title=\"GitHub | Gerard Solé i Castellví\"><strong> ");
      out.print(masterThesis.getAuthor());
      out.write("</strong></a><br>\t\t\n");
      out.write("\t\t<strong>Bio:</strong> ");
      out.print(masterThesis.getBio());
      out.write("</p>\t\n");
      out.write("\t</div>\n");
      out.write("\t<h2>Summary</h2>\n");
      out.write("\t<p style=\"text-align: justify;\">\n");
      out.write("\t\t<img src=\"");
      out.print(masterThesis.getSmallPhoto());
      out.write("\" width=\"125\" align=\"left\" style=\"margin:0 10px 0 0;\"/>\n");
      out.write("\t\t");
      out.print(masterThesis.getDescription());
      out.write("</p>\n");
      out.write("\t\n");
      out.write("\t<div>\n");
      out.write("\t\t<img align=\"middle\" src=\"");
      out.print(masterThesis.getBigPhoto());
      out.write("\" width=\"350\">\n");
      out.write("\t\t<p align=\"center\">Fig. 1 – Nice Picture :D</p>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<p style=\"text-align: justify;\">\n");
      out.write("\t\t");
      out.print(masterThesis.getTopic());
      out.write("</p>\n");
      out.write("\t<h2>Want to know more?</h2>\n");
      out.write("\t<div>\n");
      out.write("\t\t<strong>Directed by:</strong> <a href=\"#\" title=\"director\"><strong> ");
      out.print(masterThesis.getDirector());
      out.write("</strong></a><br>\n");
      out.write("\t\t<strong>Qualification:</strong> <a href=\"#\" title=\"Qualification\"><strong> ");
      out.print(masterThesis.getQualification());
      out.write("</strong></a><br>\n");
      out.write("\t\t<strong>Read more at:</strong> <a href=\"");
      out.print(masterThesis.getUrl());
      out.write("\" title=\"project url\"><strong>");
      out.print(masterThesis.getUrl());
      out.write("</strong></a><br>\n");
      out.write("\t\t<strong>Download at:</strong> <a href=\"");
      out.print(masterThesis.getDownloadUrl());
      out.write("\" title=\"download url\"><strong> ");
      out.print(masterThesis.getDownloadUrl());
      out.write("</strong></a>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
