/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-06-16 02:58:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.site.web.bright;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.StringEscapeUtils;
import jease.cms.domain.Content;
import jease.cms.domain.News;
import jease.cms.domain.Topic;
import jease.cms.domain.Folder;
import jease.site.Navigations;
import jfix.servlet.Servlets;
import jease.cms.domain.Content;
import jease.site.Navigations;
import java.net.URL;
import jfix.util.I18N;
import jfix.html.Html2Pdf;
import jfix.servlet.Servlets;
import jease.cms.domain.Content;
import jease.site.Navigations;

public final class Page_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


	final static String currentYear = String.format("%tY ", new java.util.Date());

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("/site/service/Pagebase.jsp", Long.valueOf(1357292604000L));
    _jspx_dependants.put("/site/service/Pdf.jsp", Long.valueOf(1357291944000L));
    _jspx_dependants.put("/site/service/Feeds.jsp", Long.valueOf(1344034858000L));
    _jspx_dependants.put("/site/service/Lightbox.jsp", Long.valueOf(1357181094000L));
    _jspx_dependants.put("/site/service/Rewrite.jsp", Long.valueOf(1357181328000L));
    _jspx_dependants.put("/site/service/Designswitch.jsp", Long.valueOf(1357181026000L));
    _jspx_dependants.put("/site/service/Jquery.jsp", Long.valueOf(1357181076000L));
    _jspx_dependants.put("/site/service/Copyright.jsp", Long.valueOf(1344034858000L));
    _jspx_dependants.put("/site/service/Prettify.jsp", Long.valueOf(1357181316000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	Content content = (Content) request.getAttribute("Node");
	Content root = (Content) request.getAttribute("Root");

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<base href=\"");
      out.print(Servlets.getContextURL(request) );
      out.print(Navigations.getBasePath((Content) request.getAttribute("Node")) );
      out.write("\" />");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n");
      out.write("<title>");
      out.print(Navigations.getPageTitle(content) );
      out.write("</title>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/site/web/bright/style/screen.css\" media=\"screen\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/site/web/bright/style/print.css\" media=\"");
      out.print( request.getParameter("print") == null ? "print" : "print,screen" );
      out.write("\" />\n");
      out.write("<link rel=\"alternate\" type=\"application/rss+xml\"  href=\"");
      out.print( request.getContextPath() );
      out.write("/site/service/feeds/rss.jsp\" title=\"RSS Feed\" />\n");
      out.write("<link rel=\"alternate\" type=\"application/atom+xml\" href=\"");
      out.print( request.getContextPath() );
      out.write("/site/service/feeds/atom.jsp\" title=\"ATOM Feed\" />");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print( request.getContextPath() );
      out.write("/site/service/jquery/jquery-min.js\"></script>");
      out.write("<script type=\"text/javascript\">//<![CDATA[\n");
      out.write("$(document).ready(function(){\n");
      out.write("\t$(\"a[href^=\\./\\~]\").each(function() { \n");
      out.write("\t\tthis.href = \"");
      out.print(request.getContextPath());
      out.write("\" + this.href.substring(this.href.indexOf(\"~\") + 1);\n");
      out.write("\t});\n");
      out.write("});\n");
      out.write("//]]></script>");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/site/service/lightbox/css/prettyPhoto.css\" type=\"text/css\" media=\"screen\" />\n");
      out.write("<style type=\"text/css\">.currentTextHolder {font-size: 12px;}</style>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print( request.getContextPath() );
      out.write("/site/service/lightbox/js/jquery.prettyPhoto.js\"></script>\n");
      out.write("<script type=\"text/javascript\">//<![CDATA[\n");
      out.write("$(document).ready(function(){\n");
      out.write("\tvar config = {\n");
      out.write("\t\t\tshow_title: true,\n");
      out.write("\t\t\tdeeplinking: false,\n");
      out.write("\t\t\tdefault_width: 640,\n");
      out.write("\t\t\tdefault_height: 480,\n");
      out.write("\t\t\toverlay_gallery: true, \n");
      out.write("\t\t\thideflash: true,\n");
      out.write("\t\t\tsocial_tools: ''\n");
      out.write("\t};\n");
      out.write("\t$(\"a.Image\").attr({\"rel\" : \"prettyPhoto[image]\"}).prettyPhoto(config);\n");
      out.write("\t$(\"a[href$=.jpg] img,a[href$=.gif] img,a[href$=.png] img\").parent().attr({\"rel\" : \"prettyPhoto[image]\"}).prettyPhoto(config);\n");
      out.write("\t$(\"a[href$=?print]\").attr({\"rel\" : \"prettyPhoto[iframe]\"}).each(function() { this.href += \"&iframe=true\";}).prettyPhoto(config);\n");
      out.write("\t");
 if (request.getParameter("print") != null) { 
      out.write("\n");
      out.write("\t\t$(\"a\").click(function(evt) {\n");
      out.write("\t\t\tif(!this.target) {\n");
      out.write("\t\t\t\twindow.parent.$.prettyPhoto.close();\n");
      out.write("\t\t\t\twindow.parent.location = this.href;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t");
 } 
      out.write("\n");
      out.write("});\n");
      out.write("//]]></script>");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/site/service/prettify/prettify.css\" media=\"all\"/>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/site/service/prettify/prettify.js\"></script> \n");
      out.write("<script type=\"text/javascript\">//<![CDATA[\n");
      out.write("$(document).ready(function(){\t\n");
      out.write("\t$(\"code,pre\").addClass(\"prettyprint\");\n");
      out.write("\tprettyPrint();\n");
      out.write("});\n");
      out.write("//]]></script>");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div id=\"wrap\">\n");
      out.write("\t<div id=\"header\">\n");
      out.write("\t\t<h1 id=\"logo\">\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.print(root.getPath());
      out.write("\">\n");
      out.write("\t\t\t");
 for(char c : root.getTitle().toCharArray()) { 
      out.write("<span class=\"");
      out.print( Character.isUpperCase(c) ? "green" : "" );
      out.write('"');
      out.write('>');
      out.print(c );
      out.write("</span>");
 } 
      out.write("</a>\n");
      out.write("\t\t</h1>\n");
      out.write("\t\t");
 if (((Folder) root).getContent() != null) { 
      out.write("<h2 id=\"slogan\">");
      out.print( ((Folder) root).getContent().getTitle() );
      out.write("</h2>\n");
      out.write("\t\t");
 } 
      out.write("<form method=\"get\" class=\"searchform\" action=\"");
      out.print(request.getContextPath() );
      out.print(root.getPath());
      out.write("\">\n");
      out.write("\t\t<p>\n");
      out.write("\t\t\t<input type=\"text\" name=\"query\" class=\"textbox\" value=\"");
      out.print(request.getParameter("query") != null ? StringEscapeUtils.escapeXml(request.getParameter("query")) : "");
      out.write("\" />\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"page\" value=\"/site/service/Search.jsp\" />\n");
      out.write("\t\t\t<input type=\"submit\" class=\"button\" value=\"Search\" />\n");
      out.write("\t\t</p>\n");
      out.write("\t\t</form>\n");
      out.write("\t\t<div id=\"tabs\">\n");
      out.write("\t\t<ul>\n");
      out.write("\t\t");

			String currentPath = content.getPath();
			for (Content tab : Navigations.getTabs(root)) {
				String tabPath = tab.getPath();
				boolean current = currentPath.startsWith(tabPath + "/");
			
      out.write('<');
      out.write('l');
      out.write('i');
      out.print(current ? " class=\"current\"" : "");
      out.write(">\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.print(tabPath);
      out.write("\"><span>");
      out.print(tab.getTitle());
      out.write("</span></a>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t");

				}
			
      out.write("</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id=\"content-wrap\">\n");
      out.write("\t\t\t<div id=\"photo\"></div>\n");
      out.write("\t\t\t\t<div id=\"leftbar\">\n");
      out.write("\t\t\t\t\t<h1><a href=\"");
      out.print(request.getContextPath() );
      out.print(content.getParent().getPath());
      out.write('"');
      out.write('>');
      out.print(((Content) content.getParent()).getTitle());
      out.write("</a></h1>\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t");

						for (Content item : Navigations.getItems((Content) content.getParent())) {
							if (item instanceof Topic) {
					
      out.write("</ul>\n");
      out.write("\t\t\t\t\t\t<h1>");
      out.print(item.getTitle());
      out.write("</h1>\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t");
 } else { 
      out.write("<li ");
      out.print(item == content ? " class=\"current\"" : "");
      out.write(">\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.print(item.getPath());
      out.write('"');
      out.write('>');
      out.print(item.getTitle());
      out.write("</a>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t");
 } 
 } 
      out.write("</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"main\">\n");
      out.write("\t\t\t\t<div id=\"breadcrumb\">\n");
      out.write("\t\t\t\t");
 for (Content parent : Navigations.getBreadcrumb(root, content)) { 
      out.write("\n");
      out.write("\t\t\t\t\t&raquo; <a href=\"");
      out.print(request.getContextPath() );
      out.print(parent.getPath());
      out.write('"');
      out.write('>');
      out.print(parent.getTitle());
      out.write("</a>\n");
      out.write("\t\t\t\t");
 } 
      out.write("</div>\n");
      out.write("\t\t\t\t");
 pageContext.include((String) request.getAttribute("Page.Template")); 
      out.write("<div style=\"clear: both\"></div>\n");
      out.write("\t\t\t\t<div id=\"editorial\">\n");
      out.write("\t\t\t\t");
 Content latestChange = Navigations.getLatestContribution(content); 
      out.write("\n");
      out.write("\t\t\t\t\tLast modified on ");
      out.print(String.format("%tF", latestChange.getLastModified()));
 if (latestChange.getEditor() != null) { 
      out.write("\n");
      out.write("\t\t\t\t\t\tby ");
      out.print(latestChange.getEditor().getName());
 }
      out.write("</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"rightbar\">\n");
      out.write("\t\t\t");

				Content newsContext = (Content) content.getParent();
				for (News news : Navigations.getNews(newsContext)) {
			
      out.write("<h1><a href=\"");
      out.print(request.getContextPath() );
      out.print(news.getPath());
      out.write('"');
      out.write('>');
      out.print(news.getTitle());
      out.write("</a></h1>\n");
      out.write("\t\t\t\t");
 if (news.getDate() != null) { 
      out.write("<p class=\"news-date\">");
      out.print(String.format("%tF", news.getDate()));
      out.write("</p>\n");
      out.write("\t\t\t\t");
 } 
 if (StringUtils.isBlank(news.getTeaser())) { 
      out.print(news.getStory());
 } else { 
      out.write("<p>\n");
      out.write("\t\t\t\t\t");
      out.print(news.getTeaser());
      out.write("<br />\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.print(news.getPath());
      out.write("?print\">More...</a>\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t");
 } 
 } 
      out.write("</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div id=\"footer\">\n");
      out.write("\t\t<div class=\"footer-left\">\n");
      out.write("\t\t\t<p class=\"align-left\">\n");
      out.write("\t\t\t\t");
      out.write("\n");
      out.write("&copy; ");
      out.print( currentYear );
      out.write("<a href=\"http://jease.org/\">jease.org</a>");
      out.write(' ');
      out.write('|');
      out.write(' ');

	String pdfPath = request.getParameter("path");
	if (pdfPath != null) {
		Content pdfContent = (Content) Navigations.getRoot().getChild(pdfPath);
		URL pdfUrl = new URL(request.getScheme() + "://" + Servlets.getHost(request) 
								+ request.getContextPath() + Navigations.getBasePath(pdfContent));
		byte[] pdfBytes = new Html2Pdf(pdfUrl).getBytes();
		response.setContentType("application/pdf");
		response.setHeader("Content-Disposition","inline; filename=" + pdfContent.getId() + ".pdf"); 
		response.setContentLength(pdfBytes.length);
		response.getOutputStream().write(pdfBytes);
		return;
	} else {

      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/site/service/Pdf.jsp?path=");
      out.print(((Content) request.getAttribute("Node")).getPath() );
      out.write("\" rel=\"noindex, nofollow\">");
      out.print(I18N.get("Page_as_PDF"));
      out.write("</a>\n");
 } 
      out.write("<br />\n");
      out.write("\t\t\t\t");
 if (!jease.Registry.getParameter(jease.Names.JEASE_SITE_DESIGN,"").startsWith("/")) { 
      out.write("\n");
      out.write("Design\n");
 for (String design : new String[] { "bright", "cool", "loop", "photo", "robot", "simple" }) { 
      out.write("\n");
      out.write(" | <a href=\"?design=");
      out.print(design);
      out.write('"');
      out.write('>');
      out.print(design);
      out.write("</a>\n");
 } 
 } 
      out.write("</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"footer-right\">\n");
      out.write("\t\t\t<p class=\"align-right\">Design by <a href=\"http://www.styleshout.com/\">styleshout</a></p>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
